### ISSUE TITLE
'MQTTClient/MQTTClient.h' file not found

### ISSUE THREAD

**Issue by j8** [tuanpmt/react-native-mqtt#6]
Hi, when trying to build the library I always get:

<img width="1361" alt="screen shot 2016-03-19 at 11 30 05" src="https://cloud.githubusercontent.com/assets/818400/13898092/a2e7854e-edc7-11e5-8889-55edfb4f32e1.png">

**Comment by j8** [comment]
I managed to resolve this by removing the Podfile.lock and running ```pod install``` again. But now has another issue:

```
Undefined symbols for architecture arm64:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in libRCTMqtt.a(SRWebSocket.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by j8** [comment]
Linking libicucore.tbd seems to fix the issue.

**Comment by aestrro** [comment]
I'm actually running into the same issue. But I am unable to resolve it like you did with removing the Podfile.lock followed by the pod install. 

Are you saying that you link libicucore.tbd to < your project folder >?

**Comment by j8** [comment]
@aestrro you need to link  libicucore.tbd  in your build phases

<img width="1652" alt="screen shot 2016-04-08 at 13 48 46" src="https://cloud.githubusercontent.com/assets/818400/14382800/c11412fc-fd90-11e5-80a2-e901fc9bd5be.png">

**Comment by aestrro** [comment]
Well... that worked, and yes adding that to the README would be splendid :+1:

**Comment by j8** [comment]
Nice that it worked for you, I'll open a pool request for enhancing the README. Also I have few major fixes, as the react native library is not passing correctly params to the the native mqtt lib

**Comment by aestrro** [comment]
That's awesome, I'll definitely keep an eye out. Now that this has been resolved for me I am trying to call methods like this:

`
// accessing 'publish' outside of .then(function(client) {}) scope
client.subscribe( '#' ,0);
client.publish( '/dest/' , JSON.stringify({ 'name':'aestrro' }), 0, false );
`

Anyways, thanks for everything, I'm going to pick this back up on Monday. If you have any tips, please let me know..

**Comment by carpogoryanin** [comment]
Doing like you, but have this error after `pod install`
```
[!] Unable to find host target(s) for RCTMqtt. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)
```
May be someone know how to fix it?

**Comment by lucascardial** [comment]
I have the same problem. Has anyone managed to fix this?
